language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
addons:
  sauce_connect: true
env:
  global:
  - secure: Tq5Hi9P2I8AmOWwMc0/P/fELtXthxGCPjRiMGo7kUtPhFvlrFUVM7mN7LpLTK+PFOkoKbVXcwZbvQGW7KwK8028vQFbn17n6tk3nDZeM7PCcS6h/mEits33CFKbGE+y6EK7WPdil/TQbqow8WjhaNqqoLCSneQsbiSHkOVa+scg=
  - secure: M3ZCnB7QCMnhAn/7ViM/N1cIk4R3xvzfaAO8N6xQMaF6z/VkVXCoQfLcafWlDILFLP/uEOx1ptBV+WsgOavDCgfRQdZY/BMcpXhaGwq5oHdIInLZn28zetPJFkJ2lI+8DXma/ukatq87pQQozFdCnFjdsEVFN1+QesOthpO+3e0=
  - secure: FM8nwQVLYRTZ8/Ujkugz9Yh3VcV8v7b9FBtk/KWEWtNJSXNDDta8+vCqAo1JQXh1NZs6qMaoAPJEMXOQ/UMq2LoMiSem4pHQbVO5I/Q/6K1i+LRbnBqmbkHFHd1NZ1ZthwgY+86opb+xUVHAeAh27pam4M2jM9ahsH5vMjezyPs=
