language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
addons:
  sauce_connect: true
env:
  global:
  - secure: UrCt1iaT0zWUl5dJ5/F/s51tZi6pl7wuJ/sI0S2MDgcUEwHrI8OSbE6etBPwRlTh+qnVOFJ4nFUx1ZksxhR5kZFJSxk4DXxWtIIjP68F3W4qpng/gZQLuYTE2zDUGE5RUNYg22KreGsxqGeo0pP2EmU7dyA48Wcdt5JvytXrAFY=
  - secure: gm/Z62X4A8Doaw12FOm0D1kFVsI4jAtpp46jByTsn9+GfZThUgpwTLVRfSgH70woCdXz4/alXGYTol0Zz1vvwzraU8n6jjYXhrnZVS+XT4157d+69xOBvBK9LFsN19s0SdJ6rk48PQJu5lZEJGvpQXYosfMKrVKPp/wqF5Q5nfA=
  - secure: g17fuQ0EbqT1K5RvzEyHvDaYNHOp2MECzKhMCDiMqJSxG6FfvM5CQhE4vKOnqhDnqRpH5/M1ZKMzEpC2zDdr8qP+rhqIe1F396OMFa0hhhNCXTM1Ca1nZ7zMJki+gCQuvbmKM8CDz49Pn5yH1rDdAvt3mw+m64TDuD2tWniz8GY=
