language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
env:
  global:
  - secure: UrCt1iaT0zWUl5dJ5/F/s51tZi6pl7wuJ/sI0S2MDgcUEwHrI8OSbE6etBPwRlTh+qnVOFJ4nFUx1ZksxhR5kZFJSxk4DXxWtIIjP68F3W4qpng/gZQLuYTE2zDUGE5RUNYg22KreGsxqGeo0pP2EmU7dyA48Wcdt5JvytXrAFY=
